
services:
    BeyondBlueSky\OAuth2PKCEClient\Repository\OAuth2SessionRepository:
        class: BeyondBlueSky\OAuth2PKCEClient\Repository\OAuth2SessionRepository
        public: true
        autowire: true
    BeyondBlueSky\OAuth2PKCEClient\DependencyInjection\OAuth2PKCEClientExtension:
        class: BeyondBlueSky\OAuth2PKCEClient\DependencyInjection\OAuth2PKCEClientExtension
        public: true
        autowire: true
        arguments:  ['server_uris','client', '@BeyondBlueSky\OAuth2PKCEClient\Repository\OAuth2SessionRepository']
        
        
